"use client";

import { Fragment, useMemo, useState } from "react";
import { Edit, Info, Plus, Trash2 } from "lucide-react";
import {
  RoleIncludeDTO,
  useRolesAndPermissions,
} from "@/lib/hooks/useRolesPermissions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { RoleFormDialog } from "@/components/admin/RoleFormDialog";
import { DeleteRoleDialog } from "@/components/admin/DeleteRoleDialog";

/**
 * Default roles are those *not* generated by the `roles_insert` stored
 * procedure. The proc always creates IDs prefixed with `ROLE`, so anything
 * else (e.g. `ADMIN`, `EMPLOYEE`, `SUPERADMIN`) is treated as read-only.
 *
 * The legacy Razor page disagreed with itself about this rule (it later
 * partitioned on RolDesc); we standardize on the `RolId.startsWith("ROLE")`
 * test, which matches the data the stored proc actually emits.
 */
function isCustomRole(role: RoleIncludeDTO): boolean {
  return Boolean(role.RolId && role.RolId.startsWith("ROLE"));
}

export function RoleManagementTable() {
  const { data: rolesAndPermissions = [], isLoading } = useRolesAndPermissions();
  const [editTarget, setEditTarget] = useState<RoleIncludeDTO | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<RoleIncludeDTO | null>(null);
  const [showAdd, setShowAdd] = useState(false);
  const [expandedRoleId, setExpandedRoleId] = useState<string | null>(null);

  const defaultRoles = useMemo(
    () => rolesAndPermissions.filter((r) => !isCustomRole(r)),
    [rolesAndPermissions],
  );
  const customRoles = useMemo(
    () => rolesAndPermissions.filter(isCustomRole),
    [rolesAndPermissions],
  );

  if (isLoading) {
    return (
      <div className="space-y-3 p-4">
        {[...Array(4)].map((_, i) => (
          <Skeleton key={i} className="h-12 w-full" />
        ))}
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-semibold">Role Management</h2>
        <Button onClick={() => setShowAdd(true)}>
          <Plus className="w-4 h-4 mr-1" />
          Add Role
        </Button>
      </div>

      <section>
        <div className="flex items-center gap-2 mb-3">
          <h3 className="text-lg font-semibold">Default Roles</h3>
          <span
            className="text-muted-foreground"
            title="These are default roles bundled with the system. They cannot be edited or deleted, but their permissions can be copied when creating a new role."
          >
            <Info className="w-4 h-4" />
          </span>
          <Badge variant="secondary">Read-only</Badge>
        </div>
        {defaultRoles.length === 0 ? (
          <p className="text-sm text-muted-foreground">No default roles configured.</p>
        ) : (
          <div className="overflow-x-auto rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[200px]">Role Name</TableHead>
                  <TableHead>Permissions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {defaultRoles.map((role) => (
                  <TableRow key={role.RolId}>
                    <TableCell className="font-medium">
                      {role.RolName || role.RolId}
                    </TableCell>
                    <TableCell>
                      {role.RolesAndPermissionNav.length === 0 ? (
                        <span className="text-muted-foreground">No permissions assigned.</span>
                      ) : (
                        <div className="flex flex-wrap gap-1">
                          {role.RolesAndPermissionNav.map((perm) => (
                            <Badge
                              key={`${role.RolId}-${perm.ArpPer}`}
                              variant="outline"
                              title={perm.ArpPerDesc ?? ""}
                            >
                              {perm.ArpPerName ?? perm.ArpPer}
                            </Badge>
                          ))}
                        </div>
                      )}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}
        <p className="text-xs text-muted-foreground mt-2">
          Default roles cannot be edited or deleted.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold mb-3">Custom Roles</h3>
        {customRoles.length === 0 ? (
          <div className="rounded-md border p-6 text-center text-sm text-muted-foreground">
            <p>The system does not have a custom role yet besides the defaults.</p>
            <p>Click &quot;Add Role&quot; above to create one.</p>
          </div>
        ) : (
          <div className="overflow-x-auto rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[260px]">Role Name</TableHead>
                  <TableHead>Description</TableHead>
                  <TableHead className="w-[160px] text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {customRoles.map((role) => {
                  const isExpanded = expandedRoleId === role.RolId;
                  return (
                    <Fragment key={role.RolId}>
                      <TableRow
                        className="cursor-pointer hover:bg-muted/50"
                        onClick={() =>
                          setExpandedRoleId(isExpanded ? null : role.RolId)
                        }
                      >
                        <TableCell className="font-medium">
                          {role.RolName || role.RolId}
                        </TableCell>
                        <TableCell>{role.RolDesc || "-"}</TableCell>
                        <TableCell className="text-right">
                          <div className="flex justify-end gap-2">
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={(e) => {
                                e.stopPropagation();
                                setEditTarget(role);
                              }}
                            >
                              <Edit className="w-4 h-4" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={(e) => {
                                e.stopPropagation();
                                setDeleteTarget(role);
                              }}
                            >
                              <Trash2 className="w-4 h-4 text-red-500" />
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                      {isExpanded && (
                        <TableRow className="bg-muted/30">
                          <TableCell colSpan={3}>
                            <h4 className="text-sm font-semibold mb-2">Permissions</h4>
                            {role.RolesAndPermissionNav.length === 0 ? (
                              <p className="text-sm text-muted-foreground">
                                No permissions assigned.
                              </p>
                            ) : (
                              <div className="flex flex-wrap gap-1">
                                {role.RolesAndPermissionNav.map((perm) => (
                                  <Badge
                                    key={`${role.RolId}-perm-${perm.ArpPer}`}
                                    variant="outline"
                                    title={perm.ArpPerDesc ?? ""}
                                  >
                                    {perm.ArpPerName ?? perm.ArpPer}
                                  </Badge>
                                ))}
                              </div>
                            )}
                          </TableCell>
                        </TableRow>
                      )}
                    </Fragment>
                  );
                })}
              </TableBody>
            </Table>
          </div>
        )}
      </section>

      <RoleFormDialog
        mode="add"
        open={showAdd}
        onOpenChange={setShowAdd}
        copyOptions={rolesAndPermissions}
      />
      <RoleFormDialog
        mode="edit"
        open={Boolean(editTarget)}
        onOpenChange={(value) => {
          if (!value) setEditTarget(null);
        }}
        role={editTarget}
        copyOptions={rolesAndPermissions.filter((r) => r.RolId !== editTarget?.RolId)}
      />
      <DeleteRoleDialog
        open={Boolean(deleteTarget)}
        onOpenChange={(value) => {
          if (!value) setDeleteTarget(null);
        }}
        role={deleteTarget}
      />
    </div>
  );
}
